export const PATH_NAME = {
  ROOT: '/dashboard/statistics',
  LOGIN: '/login',
  REGISTER: '/register',
  STATISTICS: '/dashboard/statistics',
  ANALYTICS: '/dashboard/analytics',
  MAIL: '/application/mail',
  PORTFOLIO: '/application/user/portfolio',
  PRIVACY_POLICY: '/privacy-policy',
  FORGOT_PASSWORD: '/forgot-password',
  USER_LIST: '/user',
  USER_CREATE: '/user/create',
  USER_EDIT: '/`user/edit/:id',
  USER_SHOW: '/user/show/:id',
};
