export const PATH_NAME = {
  ROOT: '/dashboard/statistics',
  LOGIN: '/login',
  REGISTER: '/register',
  STATISTICS: '/dashboard/statistics',
  ANALYTICS: '/dashboard/analytics',
  MAIL: '/application/mail',
  PORTFOLIO: '/application/user/portfolio',
  PRIVACY_POLICY: '/privacy-policy',
  FORGOT_PASSWORD: '/forgot-password',
  USER_LIST: 'application/user/list',
  USER_CREATE: 'application/user/create',
  USER_EDIT: 'application/`user/edit/:id',
  USER_SHOW: 'application/user/show/:id',
};
